package njbh.autism.demo.controller;

import njbh.autism.demo.model.User;
import njbh.autism.demo.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.UUID;

@Controller //This means that this class is a controller
@RequestMapping(path = "/survey") //this means url starts with /survey after application path
public class MainController {
    @Autowired //this means to get the bean called userRepository which is auto-generated by Spring, we could use it to handle the data
    private UserRepository userRepo;

    @PostMapping(path = "/addUser")
    public @ResponseBody
    String addUser (@RequestParam String name,
                    @RequestParam String email,
                    @RequestParam String birthday,
                    @RequestParam int age) {  //input format to yyyy-MM-dd
        User p = new User();
        p.setId(UUID.randomUUID());
        p.setName(name);
        p.setEmail(email);
        p.setDate(java.sql.Date.valueOf(birthday));
        p.setAge(age);
        userRepo.save(p);
        return "saved";
    }

    @GetMapping(path = "/allUsers")
    public @ResponseBody Iterable<User> getAllUsers() {
        return userRepo.findAll();
    }
}
